### ISSUE TITLE
variable using Color() should be named tuples

### ISSUE THREAD

**Issue by jbmorizot** [jenskutilek/RoboChrome#1]
It seems with the new FonTools if you make a new Color() object you need to fill the four values and if you want to change one, you can't access it with its name (variable. red).
So `color = fontTools.ttLib.tables.C_P_A_L_.Color()` doesn't works and `color.red = Value` neither.

**Comment by jbmorizot** [comment]
Precision Color() instances should be namedTuple :-)

**Comment by jenskutilek** [comment]
Thank you! Merged your pull request.

**Comment by jbmorizot** [comment]
My pleasure! glad to have been able to help.
