### ISSUE TITLE
Robochrome not opening from extensions menu

### ISSUE THREAD

**Issue by MauriceMeilleur** [jenskutilek/RoboChrome#3]
Jens: I can't get Robochrome to open from Extensions. It shows up in the menu, I can get to the help file, but the extension window itself doesn't open up—click the title and nothing happens. I've tried both with one of my UFO files and one of your demos, FF Copa, open. I'm using Mojave and RF 3.3.

**Comment by jenskutilek** [comment]
Please try to update RoboChrome through Mechanic, it should be fixed now.

**Comment by MauriceMeilleur** [comment]
Thanks, Jens—it appears to be working just fine now.
